services:
  postgres:
    image: postgres:10
    container_name: postgres_container_agrixDB
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agrix_db
    ports:
      - "5432:5432"
    volumes:
      - /home/danilo-couto/Git Repositories/java-001-projeto-final-agrix-fase-c/data/postgres
